### ISSUE TITLE
Uncaught ReferenceError: React is not defined

### ISSUE THREAD

**Issue by monte-hayward** [loopj/react-inline-svg#2]
code

```
import React from 'react';
import InlineSVG from 'react-inline-svg';
// ...
<InlineSVG className="toggle" src="/public/images/video_controls_volume_icon.svg" />
```

`Uncaught ReferenceError: React is not defined
(anonymous function)    @   react-inline-svg.js:45`

**Comment by jmshal** [comment]
The library currently doesn't support CommonJS module loading, or even UMD for that matter.

@loopj Would you be alright for me to UMD this bad boy? Also, how exactly is this accomplished for Bugsnag, I was under the impression you guys use browserify/webpack?

**Comment by loopj** [comment]
@jacobmarshall that would be awesome, I'm not super familiar with UMD stuff so would gladly merge a PR

**Comment by jmshal** [comment]
Hey @monte-hayward, would you mind changing the `react-inline-svg` section of your `package.json` to something like the following - and letting me know if all is working? I just want to verify that the changes I have made, work in your setup.

``` json
{
  "dependencies": {
    "react-inline-svg": "jacobmarshall/react-inline-svg#umd"
  }
}
```

If you're using browserify, it should be all good, I haven't tested with webpack.

Cheers,
Jacob

**Comment by pcorpet** [comment]
@loopj, could you do a release so we can benefit from this fix directly in NPM,  please?
